apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: zhaoyang
  labels:
    name: k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        env:
        - name: HOSTNAME_COMMAND
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: 18272903310/k8s-demo
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /Health
            port: 80
          timeoutSeconds: 5


---

apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
  namespace: zhaoyang
spec:
  type: NodePort
  selector:
    app: k8s-demo
  ports:
  - port: 80
    nodePort: 32225
    targetPort: 80
    
